### ISSUE TITLE
Improve development process on Docker Compose environment

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#101]
Currently, the `worker` and `accesspoc` services need to be restarted each time changes are made over the related source code. Additionally, with the move from CSS to SCSS in #100, when styles changes are made, the CSS file needs to be compiled. To avoid having to do this changes manually we could:

**Gunicorn (DONE)**
Use the `--reload` setting when running the worker:

http://docs.gunicorn.org/en/stable/settings.html#reload

**Celery**
Use `watchdog` to monitor file changes and reload the worker:

https://avilpage.com/2017/05/how-to-auto-reload-celery-workers-in-development.html

**SASS**
Use `django-compressor` to build and compress CSS when needed per request (it could also be used to bundle and compress all Javascript code):

https://django-compressor.readthedocs.io/en/latest/

**Comment by jraddaoui** [comment]
Estimate 6 hours.

**Comment by jraddaoui** [comment]
Added the `--reload` flag in 9ad969b.

**Comment by stefanabreitwieser** [comment]
Hi @jraddaoui -- this is just a go-ahead for taking care of this as a "bonus issue" during this sprint if you have time. Thanks!!

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser,

Not sure if someone on your end is using the Docker Compose environment to test this changes. Please, let me know if you want me to add further notes to test it if that's the case. Otherwise, this could be closed.

**Comment by stefanabreitwieser** [comment]
Hi @marcbouchercca -- are you using Docker Compose for this? If not, you can close this issue. Thanks!

**Comment by marcbouchercca** [comment]
Hi @stefanabreitwieser,
We are not using Docker for our environments.
Thanks.
