### ISSUE TITLE
Use a package manager to manage front-end dependencies

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#102]
The following front-end dependencies are currently "vendored" in the application:

- jQuery.
- Bootstrap.
- Popper.
- Font Awesome.
- Roboto.

We should be using a package manager like NPM to handle them and avoid to be tracking all their code in this repository.

**Comment by stefanabreitwieser** [comment]
Hi @jraddaoui -- this is just a go-ahead for taking care of this as a "bonus issue" during this sprint if you have time. Thanks!!

**Comment by jraddaoui** [comment]
Some important notes about this changes:

- @stefanabreitwieser: the repository admins should get notifications from Github if there are vulnerabilities in the front-end dependencies. Similar to what `pyup` does with the back-end dependencies but without being fully integrated in the CI process.
- @bunekcca: the test instance is now updated and using the latest versions of the front-end dependencies. Due to that upgrade I had to fix a couple of elements in the UI. Please, let me know if you find something else.
- @marcbouchercca: I made some changes in the install docs with what is needed to manage and build those dependencies in production. Please, let me know if you need more information.

**Comment by stefanabreitwieser** [comment]
Thanks Radda! @bunekcca if everything is okay with the UI, you can close this ticket -- thanks!

**Comment by bunekcca** [comment]
hi @jraddaoui, I don't see changes. Could you tell me what have been changed UX wise ?

**Comment by jraddaoui** [comment]
Hi @bunekcca,

That's great, ideally nothing should be changed as it's just a minor upgrade of the Bootstrap dependency (4.1 > 4.3). One of the things I noticed was that the "See more" buttons in the tables took to lines instead of one when the description column was to big, something that I already fixed. I just want to double check that I didn't miss something else.

Thanks!
