### ISSUE TITLE
Problem: related DigitalFiles not deleted from the ES index when deleting a Collection or Folder

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#123]
Additionally, when a Collection is deleted, the related Folders DublinCore model persists in the database too. This is caused by the removal of signal handlers in #122 because the new `delete` method is not called for the related models on a cascading delete.

This could be easily fixed by reverting [this commit](https://github.com/CCA-Public/dip-access-interface/commit/32c384217b4862746c9f496cad686ff846facd47) but, it may be a good idea to only use the `pre_delete` signal handler to remove the related DublinCore model and use the new Celery task to remove all descendants from ES, avoiding multiple delete request to ES in the same page load.

**Comment by jraddaoui** [comment]
Hi @cole and @sevein,

This is the issue that came out after moving from a `pre_delete` signal handler to a custom `delete` method in the model class. The pre-delete process is needed at this point for two reasons:

- Delete a relation with a DublinCore model from Collection and DIP models:

The DublinCore model is used to extend the Collection and DIP models and the one to one relation is made from both, the Collection and DIP tables. Ideally, we would have a base model reflected in the database to be able to make the relation with DublinCore from there and use "on delete cascade". But, at this point, that would require a lot more work than "restoring" the `pre_delete` signal handler, only for Collections and DIPs and only removing the related DublinCore (see WIP PR: #124).

- Delete the related document on the Elasticsearch index:

In this case, I think it's good that the custom `delete` method doesn't get called on cascading delete and that we should not re-add the ES delete request to the signal handler, as that creates a request for each descendant, which may be an issue when deleting a huge Collection/DIP. Instead, we could use a "_delete_by_query" request to the needed indexes using the ancestor id from a new Celery task.

Any other idea or feedback would be really appreciated. Thanks!

**Comment by cole** [comment]
Hi @jraddaoui,

that's a perfectly good use case for signals, sorry for steering you wrong! I'm not sure if I made the point clearly to @sevein, but there are valid use cases for signals. The one I usually think of is if you are trying to hook into an external model that's outside of your control (e.g. the Django `User` model), but apparently cascading delete is also one.

PR #124 looks good to me.

**Comment by jraddaoui** [comment]
Thanks and np @cole! It gives us the chance to improve the delete process a bit more.

**Comment by jraddaoui** [comment]
Some notes for testing:

Similar to #53, when a collection or folder is deleted, if it has descendants, a notification should be shown to the user informing about a background task being executed to remove the descendants from the Elasticsearch indexes. After the task finished, the collection or folder files should not appear in the search page.

**Comment by sallain** [comment]
This seems to be working fine. Deleting a folder gives a notification about the background task and the folder is removed; same for a collection. Ready for CCA to test.

**Comment by stefanabreitwieser** [comment]
Looks good, thanks!
