### ISSUE TITLE
Add continuous integration process

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#13]
- Add [tox](http://tox.readthedocs.io/en/latest/) to automate testing and syntax checks.
- Add [Travis CI](https://travis-ci.org/) to run tox on each commit/PR.

You can find a good example in our automation-tools repository, check:
- https://github.com/artefactual/automation-tools/blob/master/tox.ini
- https://github.com/artefactual/automation-tools/blob/master/.travis.yml

**Comment by jraddaoui** [comment]
I have configured Codecov and pyup in the project and sent Github apps request for both of them.

Once they are approved I think we can call this done.

**Comment by stefanabreitwieser** [comment]
@jraddaoui I thought we had approved the third-party apps last week -- do you still need approval from us for this? If it didn't go through for whatever reason, please feel free to send the requests again. Thanks!

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser,

I've re-sent he Codecov request; pyup looks to be accepted, but the checks are not being triggered, for example in the feature files PR I just created, I'm not sure why.

**Comment by stefanabreitwieser** [comment]
@jraddaoui Just accepted Codecov request -- let me know if there's anything else I can do to help.

**Comment by jraddaoui** [comment]
Thanks @stefanabreitwieser, but it looks like something else is needed. Maybe you need to go to the repository settings and enable the Webhocks, or something in the Integrations and Services section.

**Comment by stefanabreitwieser** [comment]
@jraddaoui I went in and configured Codecov -- it should be working, but if not, I've just given you admin privileges if you'd like to set it up yourself. I'll flip you back tomorrow morning, but let me know if you need more time.

**Comment by jraddaoui** [comment]
Pyup check is showing up in #47 and Codecov checks in #44. They should be both included in following PRs.

Thank you @stefanabreitwieser!

**Comment by jraddaoui** [comment]
Added some badges to the readme to show the CI status.
