### ISSUE TITLE
Add French translation for latest changes

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#139]
Hi @stefanabreitwieser and @bunekcca,

I've generated an updated version of the message files with the latest changes and, unless you want to modify them before or wait until we add a few more, some new strings a ready for translation. You can find the introduced diff useful to find those new strings:

https://github.com/CCA-Public/dip-access-interface/commit/1635c9862573f8a05615bd7ef102281b4fbdafc0#diff-379094f6bbfdaabfec3a2e05843a3a93

**Comment by bunekcca** [comment]
Hi @stefanabreitwieser, do you take care of that?

**Comment by stefanabreitwieser** [comment]
This will be for @mireilleN !

**Comment by aqeelparpia** [comment]
Hello @stefanabreitwieser @mireilleN  could I please contribute towards this part?

**Comment by mireilleN** [comment]
Hi @aqeelparpia, thanks for offering help! 
I'm pretty much done with the strings' translations (ENG->FRA), and will do the PR this morning. So we are good for now. 
Have a great one!

**Comment by jraddaoui** [comment]
Translations added in df63fd1.

**Comment by jraddaoui** [comment]
Translations deployed in the test instance.
