### ISSUE TITLE
Set up an asynchronous task queue

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#15]
Parsing METS files can be a really time consuming operation in DIPs with a lot ofobjects and metadata. Such operation should be handled asynchronously using [Celery](http://www.celeryproject.org/) or a similar system. Check:

http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by jraddaoui** [comment]
Check the [related feature](https://github.com/CCA-Public/dip-access-interface/blob/master/features/async_processes.feature) file for more info.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser,

This has been deployed to the test server and the README file has been updated with information and install notes for the new services introduced with this feature.

There are a few things we didn't consider in the [feature file](https://github.com/CCA-Public/dip-access-interface/blob/master/features/async_processes.feature) that should also be tested:
- When an import is in progress, the Folder will appear in the Collection table with the loading icon, but it will only appear for Administrators and Editors, other users won't be able to see it.
- When an import failed, the folder will show a "See error" button in red. Clicking it will show an error message on the Folder page. Again, only for Administrators and Editors users.
- The Folder page won't be accesible by anyone when there is an import in progress for that Folder, not even knowing the URL.
- All the above should be the same for the Digital Files related to the Folder in the Search, Folder and Digital File pages.

You could have two different browsers with different user types logged in the application to test the "in progress" behavior. To produce a failure, I think you could try uploading a ZIP without a METS file.

Please, let me know if you need more information.

**Comment by stefanabreitwieser** [comment]
Hi @jraddaoui -- this looked good to me. Again, @bunekcca will want to test from a UI perspective. We'll let you know if we have any feedback on our call on Wednesday. Thanks!

**Comment by stefanabreitwieser** [comment]
Just a reminder -- thanks @bunekcca !

**Comment by bunekcca** [comment]
Hi @jraddaoui that's perfect. Thanks
