### ISSUE TITLE
Use Elasticsearch for search

### ISSUE THREAD

**Issue by timothyryanwalsh** [CCA-Public/dip-access-interface#18]

**Comment by jraddaoui** [comment]
**Sprint 1 feedback (S1-013):**

The file paths aren’t searchable unless you know the file extension. For example, if you search “lion”, nothing comes up. If you search “lion*” or “lion.svg”, a file does come up. We don’t expect that our researchers will be familiar enough with Boolean searching that they will be able to figure this out without training. Is there any way to make this more intuitive?

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, some notes about this issue and how Elasticsearch works:

When a text field is added to the ES index it's splitted in terms/tokens. See the introduction about analysis in the ES documentation:

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis.html

All text fields are currently analyzed with the standard analyzer, which doesn't split terms by a dot if it's not followed by a whitespace. The standard analyzer also uses the lowercase filter to allow case insensitive searches, but has the consequence of removing number tokens.

To achieve a similar behavior than the standard analyzer and split in dots, the following custom analyzer could be used:
```
# To split file extensions, the pattern tokenizer is used,
# which defaults to the "\W+" pattern.
analyzer(
    'filepath',
    tokenizer='pattern',
    filter=['lowercase'],
)
```
Each field in ES can use a different analyzer so we could maintain the standard analyzer in all fields except the Digital File filepath (and maybe others) where we could use that custom analyzer.

However, removing the number tokens from a path may not be ideal and I also see that the same issue could happen in other fields (like the Folder and Collection identifiers, where I see that you are using dots to split their sections and some of those sections are number tokens. E.g.: "AP185.S2.003").

Therefore, my questions are:
- In what fields do you want to split tokens by dots?
- For those fields, would you prefer to maintain the case insensitive search or the number tokens?

Please, let me know if you need more information.

**Comment by jraddaoui** [comment]
Thanks @stefanabreitwieser!

About plurals and tenses, the behavior you're expecting can be achieved by using a "stemmer" token filter and, now that you point it out, we should probably be using the "english" analyzer, which already includes the important filters for that language. One downside of it would be that you won't be able to find only exact matches for plurals and tenses.

It that's okay, we can try with the English analyzer for all text fields except for the digital files `filepath` field, where we can test the one from my previous update.

**Comment by stefanabreitwieser** [comment]
@jraddaoui That's great -- let's go ahead and use the English analyzer then. Thanks!

**Comment by jraddaoui** [comment]
This changes are also ready in the test instance.

**Comment by jraddaoui** [comment]
@stefanabreitwieser  ^^
