### ISSUE TITLE
Consider the use of a different database service

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#29]
Before moving to production we should consider a more robust database service for the application. Django abstract the database interactions so it should not require major code changes, just configuration. Knowing this will allow us to use that service in the development and test instances to prevent issues when moving to production.

**Comment by jraddaoui** [comment]
To allow querying and sorting by user groups we may introduce the use of the `GROUP_CONCAT()` function, which will limit the choices for a different database service to MySQL (already using SQLite).

**Comment by jraddaoui** [comment]
I'm starting to see this problem in the Docker environment after #70:

https://docs.djangoproject.com/en/dev/ref/databases/#database-is-locked-errors

We should really start considering this issue. In the meantime, I've increased the timeout to 30 seconds.

**Comment by sevein** [comment]
One important point they make in the docs is the following:

> Rewriting your code to reduce concurrency and ensure that database transactions are short-lived.

How long can the following code take to run?

```
        mets = METS(os.path.abspath(metsfile), dip_id)
        with transaction.atomic():
            mets.parse_mets()
```

Perhaps we shouldn't be using `atomic` in situations like the one above. Instead, we should design the task in #70 so it's idempotent/atomic/retriable. Reading http://docs.celeryproject.org/en/latest/userguide/tasks.html, the intro shares some ideas about it. Another couple of interesting links: http://celerytaskschecklist.com/ (checklist) and https://www.vinta.com.br/blog/2018/celery-wild-tips-and-tricks-run-async-tasks-real-world/ (detailed explanation).

IMO we should make an effort to stick with SQLite, but we need to understand its limitations (mostly one writer at a time and no fancy SQL queries?) and design with that constraint in mind.

**Comment by jraddaoui** [comment]
In the end, we have made the effort to make it play nice with SQLite, avoiding as possible concurrent connections. I don't have an strong opinion about using another database service at this point, so I'll close this issue, please re-open it if you feel otherwise.
