### ISSUE TITLE
Disable Django Site Administration

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#30]
The management of users and other entities should only be handled from the developed application(s).

**Comment by jraddaoui** [comment]
Estimate: 1 hour.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, sorry to bug you again.

Like #28, I'd like to address this issue as a personal contribution, to wrap things up before the beta release. But I'd like to check if you are okay with it before doing anything.

The Django Site Administration is an extra module inside the application, accessible in the `.../admin` URL only by administrator users. This module allows to modify the application data in a different way but it requires some maintenance as long as the application is developed, something that has not been done until now and that will require a little more time than removing the module.

One of the reasons I think it's better to remove it is because it may lead to corrupted data and application issues. For example, and administrator could accidentally remove one of the recently added settings through there, or move a Digital File from one Folder to another.

Another reason is because it increases the application and database size, as the module needs to be loaded and a few tables are needed, that's why this could be a great moment to do it, before a final set of migrations is created for the Beta release in #78.

Please, let me know what you think.

**Comment by stefanabreitwieser** [comment]
Hi @jraddaoui -- no worries! I'm going to tag @marcbouchercca here in case he has feedback, but this looks good to me. Thank you so much for all your work on this!

**Comment by marcbouchercca** [comment]
Hello @jraddaoui, looks good to me as well.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, @marcbouchercca,

This is also deployed to the test instance. The `.../admin` URL should show now a not found page.
