### ISSUE TITLE
Navigation header collapses in small resolutions

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#33]
Only a small black bar without navigation elements is being shown in widths bellow 992px.

**Comment by jraddaoui** [comment]
**Estimate: 1h.**

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, this should be fixed in the test instance.

**Comment by stefanabreitwieser** [comment]
Looks good, thanks @jraddaoui !
