### ISSUE TITLE
Technical requirements documentation

### ISSUE THREAD

**Issue by nickwilkinson** [CCA-Public/dip-access-interface#48]
Artefactual needs to provided expanded / improved documentation about the technical infrastructure required to host this application. Initial documentation is in the [README](https://github.com/CCA-Public/dip-access-interface#installation).

**Comment by jraddaoui** [comment]
Initial system requirements in [this doc](https://docs.google.com/document/d/14bZWqF-x2tJaRbJJ_3drYUztc9rFsUugOMSfbMN8Hbw/edit).

I'll add a summary of it to the README file after #70 is merged.

**Comment by jraddaoui** [comment]
"Technologies involved" and "Recommended system requirements" sections added to README file.
