### ISSUE TITLE
Add collections page

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#52]
Similar to the home page, including the Collections table.

**Comment by jraddaoui** [comment]
Looking at the UI mock-up the changes to be made in here would be to use the current home page as the collections page and to add a big search box on top of the collections table at the home page with some extra text. That search box will lead to search page with the query. This will also require to change a few tests.

**Estimate: 3 hours.**

**Comment by jraddaoui** [comment]
Ready for review in the test server.

**Comment by bunekcca** [comment]
Hi @jraddaoui my feedback in #89

**Comment by bunekcca** [comment]
Hi @jraddaoui, that's OK for me. Thanks.
