### ISSUE TITLE
Collapse Preservation metadata section in Digital File view page

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#62]
The PREMIS events/Preservation Metadata should be hidden by default (showing just the words “Preservation metadata”). If the user clicks on the words “Preservation metadata”, the field expands to show the events. Users didn’t know what PREMIS events were and found them overwhelming to look at, but still wanted to have the information available, if less prominent.

**Comment by jraddaoui** [comment]
Use https://getbootstrap.com/docs/4.0/components/collapse/

**Comment by nickwilkinson** [comment]
CCA has decided on Option A, requiring an estimated 1hr.

**Comment by jraddaoui** [comment]
Ready for review in the test server.

**Comment by bunekcca** [comment]
Hi @jraddaoui , it works fine but the design is not OK see #90.

**Comment by jraddaoui** [comment]
If I remember well we agreed on using the default style, estimate 1 above.

**Comment by jraddaoui** [comment]
I'll close this one @bunekcca, we can follow up in #90.
