### ISSUE TITLE
Changes in header

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#64]
Changes needed in the header based on the GUI mock-up:

- White background (no separator/shadow).
- Add CCA logo.
- Add home page icon/link.
- Add link to "Collections" page (after #52).
- Move "FAQ" link to right navigation.
- Replace "Search" link with search bar.
- Add language menu (done in #16).
- Modify user and language menus caret?

**Comment by jraddaoui** [comment]
**Estimate: 8 hours**

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, this work has been deployed to the test instance.

A few changes compared with the UXPin:
- Home icon is different. We're already using FontAwesome for the icons, and that's the only home icon it has. I din't want to add a custom icon or another package only for this. Another detail is that the logo is a link to the home page too, so we could remove the home icon, or maybe you prefer that the logo redirects to your main site.
- No separators between home icon, collections and FAQ. Due to the responsive design in the header and that this separators have been removed in Bootstrap 4, I didn't to spend a lot of time on this, but let me know if you thing it's a requirement.
- Text color is lighter. This is the default from Bootstrap, which favors the hover effect.
- I have reduced the search box placeholder, following the one from the search page to make it fit in the small input.
- Language and user drop-downs. My personal opinion is that they look better with the current caret, but let me know if really want the "v" or change the globe icon with the current language.

Additionally, the header is responsive, including all navigation elements (except the logo) in an expandable menu in small resolutions.

**Comment by stefanabreitwieser** [comment]
Thanks @jraddaoui ! This looks great. @bunekcca is going to take a look at it from a UI perspective, and we'll get some feedback to you during our call next week.

**Comment by bunekcca** [comment]
Hi @jraddaoui, I'm OK with everything except these 2:

*OK for the home button icon, but we'll still keep it here and add a link to the homepage on the logo. That's the current pattern for most of the websites.
*Text color lighter, the contrast is not OK. On hover and active can we have the CCA blue ?

**Comment by jraddaoui** [comment]
Great, thanks @bunekcca!

I'm currently tweaking the Bootstrap default style variables to achieve (in a proper manner) the CCA blue tweaks and other style enhancements you already noted in other updates. About the logo and home icon, both should be already linking to the home page ;)

**Comment by stefanabreitwieser** [comment]
Hi @jraddaoui -- just a note to say that on the homepage, if you look at the "Browse Our Collections" chart,  "Identifier" is on a different line than the other column headers. Would you mind taking care of this? Hopefully a quick fix. Thanks!

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser,

It was not exactly quick, but I've been able to fix it in #100 ;)

To improve it's accessibility and style I've included the label in the sort link and the icon is now next to it, both with the same color to avoid having a light gray one top of another. To differentiate the selected sort option the label and icon will be CCA blue when selected:

![image](https://user-images.githubusercontent.com/637040/44666392-95905000-aa18-11e8-8af3-645073613123.png)

There is more feedback about the tables display from @bunekcca in other issues that I've also addressed in that PR, among other style changes. I'd appreciate if you can wait until that PR is merged and deployed to the test site to provide further style feedback.

Thanks!

**Comment by stefanabreitwieser** [comment]
No problem, thanks Radda!

**Comment by bunekcca** [comment]
Thanks for that @jraddaoui . We can close that one too.
