### ISSUE TITLE
Issues with Dublin Core fields in view pages

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#7]
Some of the DC fields do not display in the view page of `DIP` and `Collection` objects. Ideally, the ones that are empty should not display only its label.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, @nickwilkinson, @kellyannewithane,

I told you to do #6 and this issue before #10 but I didn't realize we're adding the settings page. It's not absolutely necessary to do this before #10 so I think we should move it to demo2.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, @bunekcca,

This has been deployed to the test instance.

**Comment by jraddaoui** [comment]
The settings page is accessible only by administrators through the user menu. The two Dublin Core settings created default to enable all fields and hide empty ones.

**Comment by stefanabreitwieser** [comment]
This looks super great @jraddaoui -- thanks!
