### ISSUE TITLE
Squash migrations before beta release

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#78]
After the initial back and forward in some models, there are some data migrations that could be removed and all the others could be squashed into one or two migrations. Doing it before the beta release will reduce the application code and improve the migration and tests process.

**Comment by jraddaoui** [comment]
Hi @marcbouchercca and @stefanabreitwieser,

This has been added to master and deployed to the test instance. In the end I could tweak the migrations table in the test database to match the current migrations, just in case you want to double check something in there after you install a local instance. Please, let us know when you're done with it to delete the test instance droplet.

Also, if you want the database and the uploaded DIPs from the test instance, we could pass them to you before deleting the droplet.

Best regards.

**Comment by jraddaoui** [comment]
I'll close this issue for now, please reopen it if you find any issue when you create the database in your local instance (when running `./manage.py migrate`).

**Comment by stefanabreitwieser** [comment]
Hi @jraddaoui -- feel free to delete the test instance at your convenience. We won't need the uploaded DIPs from the test instance to move to the next version since they were very much test DIPs in most cases. Thanks!
