### ISSUE TITLE
Improve Elasticsearch documents update process

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#79]
In some cases where a Collection or Folder is saved, there is no need to hit the Elasticsearch server(s) to update the related document. We should allow to enable/disable the ES document update when an object is saved. Two options:

- Add a flag to the object models to determine if the ES update should be made in the signal receivers.
- Move ES update to a custom `save` function in the models where a similar flag could be sent.

**Comment by jraddaoui** [comment]
Estimate: 6 hours.

**Comment by jraddaoui** [comment]
This is hard to test without looking at the logs in debug mode. There are some places now where a resource is saved twice but only one request to the Elasticsearch. I'd close this issue and verify that there is no problem in the Elasticsearch documents update in #53 and #123.

**Comment by sallain** [comment]
@stefanabreitwieser There isn't really any testing to do here; you can mark this as closed if #53 and #123 are functioning properly.
