### ISSUE TITLE
UI: Header

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/dip-access-interface#87]
![image](https://user-images.githubusercontent.com/38663513/44588308-54334280-a783-11e8-8819-ecd80cca0c13.png)

1. 2. 1. 1. Increase the space between "FAQ" and the search field, double the current space
2. 3. 2. 2. Font: use #343A40 for the color
3. 4. 3. 3. Hover and active states: on hover and when the item is selected it should change to the CCA blue #1D42AC
4. 5. 4. Increase the size of the logo, should be 100 px width
5. 6. Borders' colors of the search field are not the same as the button, for both use #343A40

**Comment by jraddaoui** [comment]
Thanks @bunekcca! 

Part of it is already in progress in #32, I'll try to address this feedback in the same PR.

**Comment by bunekcca** [comment]
Thanks @jraddaoui
