### ISSUE TITLE
UI: style

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/dip-access-interface#88]
![image](https://user-images.githubusercontent.com/38663513/44593199-c2323680-a790-11e8-861b-dfcbb0937284.png)

1. Use Roboto: https://fonts.google.com/specimen/Roboto
2. Double the space between "Menu above" and "Search our digital files" and between the field and "Browse our collections
3. Search field has light grey border, it should be the same color as in the header.

![image](https://user-images.githubusercontent.com/38663513/44593458-661be200-a791-11e8-9322-3afb5b95c5dd.png)

1. 1. There's a grey layer at the back to differentiate clearly the sections on the homepage (#E3E3E3)
2. 2. The counter of collections at the top is missing
3. 3. The labels of the column should be height centered
4. 4. There shouldn't be borders for the columns
5. 5. There's no date column on the homepage
6. Title column should be wider
7. 6. Use the CCA blue color for the buttons #1d42ac

**Comment by jraddaoui** [comment]
Thanks @bunekcca! 

Part of it is already in progress in #32, I'll try to address this feedback in the same PR.
