### ISSUE TITLE
UI: collection and folder page

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/dip-access-interface#89]
![image](https://user-images.githubusercontent.com/38663513/44594022-0c1c1c00-a793-11e8-9f4e-0e90af762f8c.png)
![image](https://user-images.githubusercontent.com/38663513/44594227-88166400-a793-11e8-998a-4dfcaf95f9c5.png)

1. The collection counter is missing
2. The search button has not the same design as the one in the header, please reuse the same
3. Buttons are not CCA blue #1d42ac

**Comment by jraddaoui** [comment]
Thanks @bunekcca! 

Part of it is already in progress in #32, I'll try to address this feedback in the same PR.
