### ISSUE TITLE
Problem: DIPs are duplicated across applications

### ISSUE THREAD

**Issue by kellyannewithane** [CCA-Public/dip-access-interface#98]
From user stories (IT, round 2)

-As local IT, I want to reduce redundant DIP storage by integrating SCOPE and Archivematica.

**Comment by jraddaoui** [comment]
This conflicts with #17. A possible workflow will be presented in tomorrow's meeting, which will probably require changes in the SS, the automation tools and this project. We should estimate after discussing and refining that workflow.

**Comment by jraddaoui** [comment]
Moved to #2.
